### ISSUE TITLE
Automatically set GEOSERVER_CSRF_WHITELIST from .env file

### ISSUE THREAD

**Issue by jirik** [LayerManager/layman#815]
Automatically add value of LAYMAN_PROXY_SERVER_NAME to GEOSERVER_CSRF_WHITELIST. See
https://docs.geoserver.org/latest/en/user/security/webadmin/csrf.html

It can be implemented as

```
geoserver:
      image: [docker.osgeo.org/geoserver:2.21.2](http://docker.osgeo.org/geoserver:2.21.2)
      volumes:
        - ./deps/geoserver/data:/opt/geoserver_data/
      restart: on-failure
      environment:
        - GS_VERSION=2.21.2
        - SKIP_DEMO_DATA=true
        - GEOSERVER_CSRF_WHITELIST=${LAYMAN_PROXY_SERVER_NAME}
```
